# Generated by Django 5.0.4 on 2024-05-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maskapai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_maskapai', models.CharField(max_length=255)),
                ('lokasi_maskapai', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pesawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pesawat', models.CharField(max_length=255)),
                ('jenis_pesawat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pilot', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bandara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bandara', models.CharField(max_length=255)),
                ('lokasi_bandara', models.CharField(max_length=255)),
                ('harga_tiket', models.IntegerField()),
                ('jalur', models.CharField(max_length=255)),
                ('maskapai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandara.maskapai')),
                ('pesawat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandara.pesawat')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandara.pilot')),
            ],
        ),
    ]
